import { useEffect, useState, type ReactNode } from "react";
import { Link } from "react-router-dom";
import { motion, useReducedMotion } from "framer-motion";
import { Award, BookOpen, Bot, Check, ChevronDown, Compass, FileText, Flame, GraduationCap, Languages, Leaf, Menu, Play, ShieldCheck, Sparkles, Star, Trophy, Users, X, Zap } from "lucide-react";
import { useAuth } from "../../context/AuthContext";
import { useLanguage } from "../../context/LanguageContext";
import type { Language } from "../../types";
import { getDashboardPath } from "../../utils/navigation";

const languageOptions: { code: Language; label: string }[] = [
  { code: "en", label: "EN" }, { code: "si", label: "සිං" }, { code: "ta", label: "தமி" },
];

export default function LandingPage() {
  const { user } = useAuth();
  const { t, lang, setLang } = useLanguage();
  const [menuOpen, setMenuOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const reduceMotion = useReducedMotion();
  const startPath = user ? getDashboardPath(user.role) : "/register";

  useEffect(() => {
    document.title = "FiveSamath | Gamified Learning for Sri Lankan Students";
    document.querySelector('meta[name="description"]')?.setAttribute("content", "FiveSamath is a multilingual gamified learning platform with lessons, quizzes, textbooks, exam papers, XP, badges and parent progress tracking.");
  }, []);

  const navItems = [["#home", t.landing.home], ["#features", t.landing.features], ["#subjects", t.landing.subjects], ["#how", t.landing.how], ["#parents", t.landing.parents], ["#faq", t.landing.faq]];
  const features = [
    [t.landing.featureGamified, t.landing.featureGamifiedBody, Zap], [t.landing.featureLessons, t.landing.featureLessonsBody, Compass],
    [t.landing.featureQuizzes, t.landing.featureQuizzesBody, Check], [t.landing.featureMaterials, t.landing.featureMaterialsBody, BookOpen],
    [t.landing.featurePapers, t.landing.featurePapersBody, FileText], [t.landing.featureTutor, t.landing.featureTutorBody, Bot],
    [t.landing.featureParents, t.landing.featureParentsBody, Users], [t.landing.featureLanguages, t.landing.featureLanguagesBody, Languages],
  ];
  const subjects = [["Mathematics", "Numbers, shapes and logic", "from-sky to-blue-700", BookOpen], ["English", "Books, letters and speech", "from-grape to-indigo-700", GraduationCap], ["Tamil", "Language and stories", "from-coral to-rose-700", Languages], ["Environmental Studies", "Earth, nature and discovery", "from-grass to-emerald-700", Leaf]];
  const steps = ["Choose your grade", "Pick a subject", "Open any lesson", "Complete chapters", "Take quizzes", "Earn XP and badges", "Unlock the next chapter", "Practise with papers"];
  const faqs = [
    ["What is FiveSamath?", "A gamified learning platform designed for Sri Lankan students."], ["Which grades are supported?", "Available grades and subjects are managed by the platform."], ["Are subjects different for each grade?", "Yes. Learning subjects are assigned to the student’s grade."], ["Can students access textbooks?", t.landing.noBooks], ["How does chapter unlocking work?", "Lessons can be explored while chapters unlock in a guided order."], ["Can students download papers?", "Students can access available papers and online attempts."], ["Can parents track progress?", "Parents can view linked children’s progress and learning activity."], ["Which languages are supported?", t.landing.multilingual], ["Is FiveSamath free?", t.landing.free], ["How do I create an account?", "Choose Get Started and follow the registration steps."],
  ];

  return <div className="min-h-screen overflow-x-hidden bg-cream text-ink">
    <header className="sticky top-0 z-50 border-b border-white/70 bg-cream/85 backdrop-blur-xl">
      <nav className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 lg:px-8" aria-label="Public navigation">
        <a href="#home" className="flex items-center gap-2.5 text-xl font-extrabold text-sky-dark"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-sky text-white shadow-lg shadow-sky/25"><GraduationCap size={21} /></span>{t.appName}</a>
        <div className="hidden items-center gap-5 text-sm font-bold text-ink/65 lg:flex">{navItems.map(([href, label]) => <a key={href} href={href} className="transition-colors hover:text-sky-dark">{label}</a>)}</div>
        <div className="hidden items-center gap-2 md:flex"><select value={lang} aria-label="Language" onChange={(event) => setLang(event.target.value as Language)} className="rounded-xl bg-transparent px-2 py-2 text-sm font-bold outline-none focus:ring-2 focus:ring-sky">{languageOptions.map((option) => <option key={option.code} value={option.code}>{option.label}</option>)}</select><Link to="/login" className="rounded-xl px-3 py-2 font-bold text-sky-dark hover:bg-sky/10">{t.landing.login}</Link><Link to={startPath} className="rounded-xl bg-sky px-4 py-2.5 font-extrabold text-white shadow-lg shadow-sky/25 hover:bg-sky-dark">{t.landing.join}</Link></div>
        <button type="button" aria-label={menuOpen ? "Close menu" : "Open menu"} aria-expanded={menuOpen} onClick={() => setMenuOpen((value) => !value)} className="rounded-xl p-2 focus:outline-none focus:ring-2 focus:ring-sky md:hidden">{menuOpen ? <X /> : <Menu />}</button>
      </nav>
      {menuOpen && <div className="border-t border-ink/5 bg-cream px-5 py-4 md:hidden">{navItems.map(([href, label]) => <a key={href} href={href} onClick={() => setMenuOpen(false)} className="block rounded-xl px-3 py-2.5 font-bold hover:bg-sky/10">{label}</a>)}<div className="mt-3 flex gap-2 border-t border-ink/10 pt-3">{languageOptions.map((option) => <button type="button" key={option.code} onClick={() => setLang(option.code)} className={`rounded-lg px-3 py-1.5 text-sm font-bold ${lang === option.code ? "bg-sunshine" : "bg-white"}`}>{option.label}</button>)}<Link to="/login" className="ml-auto rounded-lg px-3 py-1.5 font-bold text-sky-dark">{t.landing.login}</Link></div><Link to={startPath} onClick={() => setMenuOpen(false)} className="mt-3 block rounded-xl bg-sky px-4 py-3 text-center font-extrabold text-white">{t.landing.join}</Link></div>}
    </header>

    <main>
      <section id="home" className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-16 lg:grid-cols-[1.02fr_.98fr] lg:px-8 lg:pb-28 lg:pt-24"><div className="pointer-events-none absolute -left-32 top-10 h-72 w-72 rounded-full bg-sunshine/30 blur-3xl" /><div className="relative z-10"><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="mb-6 inline-flex items-center gap-2 rounded-full border border-sky/15 bg-sky/10 px-4 py-2 text-sm font-extrabold text-sky-dark"><Sparkles size={16} />{t.landing.trust}</motion.div><motion.h1 initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .08 }} className="max-w-2xl text-5xl font-extrabold leading-[.98] tracking-tight sm:text-6xl lg:text-7xl">{t.landing.hero}</motion.h1><motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .18 }} className="mt-6 max-w-xl text-lg font-medium leading-8 text-ink/65">{t.landing.sub}</motion.p><div className="mt-8 flex flex-wrap items-center gap-3"><Link to={startPath} className="rounded-2xl bg-sky px-6 py-3.5 font-extrabold text-white shadow-xl shadow-sky/25 hover:bg-sky-dark">{t.landing.start}</Link><a href="#features" className="inline-flex items-center gap-2 rounded-2xl border-2 border-ink/10 bg-white px-5 py-3 font-extrabold hover:border-sky/30"><Play size={16} className="fill-current text-sky" />{t.landing.explore}</a></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm font-bold text-ink/55"><span className="flex items-center gap-2"><Check size={17} className="text-grass-dark" />{t.landing.grade}</span><span className="flex items-center gap-2"><Languages size={17} className="text-grape" />{t.landing.multilingual}</span></div></div><HeroPreview reduceMotion={reduceMotion} /></section>
      <section className="border-y border-ink/5 bg-white/65"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-5 px-5 py-7 sm:grid-cols-4 lg:px-8">{[[BookOpen, t.landing.grade], [Award, t.landing.gamified], [Languages, t.landing.multilingual], [Users, "Parent progress tracking"]].map(([Icon, label]) => { const ItemIcon = Icon as typeof BookOpen; return <div key={label as string} className="flex items-center gap-2 text-sm font-bold"><ItemIcon size={19} className="shrink-0 text-sky" />{label as string}</div>; })}</div></section>
      <Section id="features" title={t.landing.featureTitle} sub={t.landing.featureSub}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(([title, body, Icon]) => { const ItemIcon = Icon as typeof Zap; return <motion.article key={title as string} whileHover={reduceMotion ? undefined : { y: -5 }} className="rounded-3xl border border-ink/5 bg-white p-5 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-sky/10 text-sky-dark"><ItemIcon size={21} /></span><h3 className="mt-5 text-lg font-extrabold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-ink/60">{body as string}</p></motion.article>; })}</div></Section>
      <Section id="subjects" title={t.landing.subjectTitle} sub={t.landing.subjectSub}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{subjects.map(([name, body, gradient, Icon]) => { const ItemIcon = Icon as typeof BookOpen; return <article key={name as string} className={`relative min-h-52 overflow-hidden rounded-3xl bg-gradient-to-br ${gradient as string} p-6 text-white shadow-lg`}><ItemIcon className="absolute -right-2 -top-2 opacity-20" size={104} /><ItemIcon size={25} /><h3 className="mt-14 text-xl font-extrabold">{name as string}</h3><p className="mt-1 text-sm text-white/75">{body as string}</p></article>; })}</div></Section>
      <Section id="how" title={t.landing.howTitle} sub={t.landing.howSub}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{steps.map((step, index) => <div key={step} className="relative rounded-2xl border-2 border-sky/10 bg-white p-4"><span className="grid h-9 w-9 place-items-center rounded-full bg-sky font-extrabold text-white">{index + 1}</span><p className="mt-4 font-extrabold">{step}</p></div>)}</div></Section>
      <section className="bg-ink py-20 text-white"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 lg:grid-cols-2 lg:px-8"><div><p className="font-extrabold tracking-[.18em] text-sunshine">XP · LEVELS · BADGES</p><h2 className="mt-3 text-4xl font-extrabold sm:text-5xl">{t.landing.gameTitle}</h2><p className="mt-4 max-w-lg leading-7 text-white/65">A mock preview of the kinds of milestones learners can work toward.</p></div><GamePreview /></div></section>
      <Section title={t.landing.bookTitle} sub={t.landing.noBooks}><div className="grid gap-5 md:grid-cols-2"><ResourceCard icon={BookOpen} title={t.landing.textbook} body={t.landing.textbookBody} tone="sky" action={t.landing.open} /><ResourceCard icon={FileText} title={t.landing.paper} body={t.landing.paperBody} tone="sunshine" action={t.landing.download} /></div></Section>
      <section id="parents" className="bg-white/70"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div><p className="font-extrabold text-grape">{t.landing.parents}</p><h2 className="mt-2 text-4xl font-extrabold leading-tight">{t.landing.parentTitle}</h2><p className="mt-4 leading-7 text-ink/60">{t.landing.parentSub}</p><Link to={user?.role === "Parent" ? "/parent" : "/register"} className="mt-7 inline-block rounded-xl bg-grape px-5 py-3 font-extrabold text-white shadow-lg shadow-grape/20">{t.landing.parentCta}</Link></div><div className="grid grid-cols-2 gap-3">{[t.landing.progress, t.landing.scores, t.landing.activity, t.landing.strengths].map((item) => <div key={item} className="rounded-2xl border border-ink/5 bg-cream p-5"><Check className="text-grass-dark" size={20} /><p className="mt-5 font-extrabold">{item}</p></div>)}</div></div></section>
      <Section title={t.landing.languageTitle} sub={t.landing.languageSub}><div className="grid gap-4 sm:grid-cols-3">{[["English", "EN", "en"], ["සිංහල", "සිං", "si"], ["தமிழ்", "த", "ta"]].map(([name, mark, code]) => <button type="button" key={code} onClick={() => setLang(code as Language)} className={`rounded-3xl border-2 bg-white p-6 text-left transition hover:-translate-y-1 hover:border-sky focus:outline-none focus:ring-2 focus:ring-sky ${lang === code ? "border-sky" : "border-ink/5"}`}><span className="text-3xl font-extrabold text-sky">{mark}</span><h3 className="mt-4 font-extrabold">{name}</h3><p className="mt-1 text-sm text-ink/55">{t.landing.languageCard}</p></button>)}</div></Section>
      <section className="bg-sky/10"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-2 lg:px-8"><div><ShieldCheck size={33} className="text-sky-dark" /><h2 className="mt-5 text-4xl font-extrabold">{t.landing.safetyTitle}</h2><p className="mt-4 max-w-xl leading-7 text-ink/65">{t.landing.safetySub}</p></div><div className="grid gap-3 sm:grid-cols-2">{[t.landing.safetyOne, t.landing.safetyTwo, t.landing.safetyThree, t.landing.safetyFour].map((item) => <div key={item} className="flex items-center gap-3 rounded-2xl bg-white p-4 font-bold"><Check size={18} className="text-grass-dark" />{item}</div>)}</div></div></section>
      <Section title={t.landing.communityTitle} sub={t.landing.communitySub}><div className="grid gap-4 md:grid-cols-3">{[[t.landing.student, t.landing.studentBody, GraduationCap], [t.landing.parent, t.landing.parentBody, Users], [t.landing.educator, t.landing.educatorBody, Compass]].map(([title, body, Icon]) => { const ItemIcon = Icon as typeof Compass; return <article key={title as string} className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-ink/5"><ItemIcon className="text-sky" size={27} /><h3 className="mt-5 text-xl font-extrabold">{title as string}</h3><p className="mt-2 leading-6 text-ink/60">{body as string}</p></article>; })}</div></Section>
      <Section id="faq" title={t.landing.faqTitle} sub={t.landing.faqSub}><div className="mx-auto max-w-3xl space-y-3">{faqs.map(([question, answer], index) => <div key={question} className="rounded-2xl border border-ink/5 bg-white"><button type="button" aria-expanded={openFaq === index} onClick={() => setOpenFaq(openFaq === index ? null : index)} className="flex w-full items-center justify-between gap-4 p-5 text-left font-extrabold focus:outline-none focus:ring-2 focus:ring-inset focus:ring-sky"><span>{question}</span><ChevronDown size={19} className={`shrink-0 transition-transform ${openFaq === index ? "rotate-180" : ""}`} /></button>{openFaq === index && <p className="px-5 pb-5 leading-7 text-ink/60">{answer}</p>}</div>)}</div></Section>
      <section className="mx-auto mb-20 max-w-7xl px-5 lg:px-8"><div className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-sky to-grape p-9 text-center text-white sm:p-14"><Star className="absolute left-8 top-8 text-sunshine/70" fill="currentColor" /><Sparkles className="absolute bottom-8 right-10 text-sunshine/70" /><h2 className="relative text-3xl font-extrabold sm:text-4xl">{t.landing.ctaTitle}</h2><div className="relative mt-6 flex flex-wrap justify-center gap-3"><Link to={startPath} className="rounded-xl bg-sunshine px-5 py-3 font-extrabold text-ink shadow-lg">{t.landing.create}</Link><Link to="/login" className="rounded-xl border-2 border-white/50 px-5 py-3 font-extrabold text-white">{t.landing.login}</Link></div></div></section>
    </main>
    <footer className="bg-ink text-white/65"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 py-12 sm:flex-row sm:justify-between lg:px-8"><div><div className="flex items-center gap-2 text-lg font-extrabold text-white"><span className="grid h-9 w-9 place-items-center rounded-xl bg-sky"><GraduationCap size={18} /></span>{t.appName}</div><p className="mt-3 max-w-xs text-sm leading-6">{t.landing.footer}</p></div><div className="grid grid-cols-2 gap-x-10 gap-y-3 text-sm font-bold sm:grid-cols-3"><a href="#home" className="hover:text-white">{t.landing.home}</a><a href="#features" className="hover:text-white">{t.landing.features}</a><a href="#subjects" className="hover:text-white">{t.landing.subjects}</a><a href="#parents" className="hover:text-white">{t.landing.parents}</a><Link to="/login" className="hover:text-white">{t.landing.login}</Link><Link to="/register" className="hover:text-white">{t.landing.join}</Link><a href="#" className="hover:text-white">About</a><a href="#" className="hover:text-white">Contact</a><a href="#" className="hover:text-white">Privacy</a></div></div><div className="border-t border-white/10 px-5 py-4 text-center text-xs lg:px-8">© {new Date().getFullYear()} {t.appName}</div></footer>
  </div>;
}

function HeroPreview({ reduceMotion }: { reduceMotion: boolean | null }) { return <motion.div animate={reduceMotion ? undefined : { y: [0, -8, 0] }} transition={{ repeat: Infinity, duration: 5 }} className="relative mx-auto w-full max-w-xl rounded-[2.5rem] bg-gradient-to-br from-sky via-sky-dark to-grape p-5 text-white shadow-2xl shadow-sky/20 sm:p-7"><Star className="absolute right-7 top-6 text-sunshine" fill="currentColor" /><div className="rounded-3xl bg-white/15 p-5 backdrop-blur"><div className="flex items-center justify-between"><span className="font-extrabold">Learning Adventure</span><Trophy className="text-sunshine" /></div><div className="mt-8 flex items-end gap-3"><span className="grid h-16 w-16 place-items-center rounded-2xl bg-sunshine text-xl font-extrabold text-ink">Lv.4</span><div><b className="text-3xl">650 XP</b><p className="text-sm text-white/70">7-day streak · 3 badges</p></div></div><div className="mt-6 h-3 rounded-full bg-white/25"><div className="h-full w-2/3 rounded-full bg-sunshine" /></div></div><div className="mt-4 grid grid-cols-3 gap-3">{[[BookOpen, "Lessons"], [Award, "Badges"], [Flame, "Streak"]].map(([Icon, label]) => { const ItemIcon = Icon as typeof BookOpen; return <div key={label as string} className="rounded-2xl bg-white/15 p-3 text-center"><ItemIcon className="mx-auto text-sunshine" size={20} /><span className="mt-2 block text-xs font-bold text-white/75">{label as string}</span></div>; })}</div></motion.div>; }
function GamePreview() { return <div className="rounded-3xl border border-white/10 bg-white/10 p-5 backdrop-blur"><div className="flex justify-between font-extrabold"><span>Level 4 Explorer</span><span className="text-sunshine">650 XP</span></div><div className="mt-4 h-4 rounded-full bg-white/15"><div className="h-full w-2/3 rounded-full bg-sunshine" /></div><div className="mt-5 grid grid-cols-3 gap-3">{["First Chapter", "Quiz Master", "7 Day Streak"].map((item) => <div key={item} className="rounded-2xl bg-white/10 p-3 text-center text-sm font-bold"><Award className="mx-auto mb-2 text-sunshine" size={20} />{item}</div>)}</div></div>; }
function ResourceCard({ icon: Icon, title, body, tone, action }: { icon: typeof BookOpen; title: string; body: string; tone: "sky" | "sunshine"; action: string }) { return <article className={`flex gap-4 rounded-3xl p-6 ${tone === "sky" ? "bg-sky/10" : "bg-sunshine/15"}`}><Icon className={tone === "sky" ? "text-sky" : "text-sunshine-dark"} size={36} /><div><h3 className="text-xl font-extrabold">{title}</h3><p className="mt-2 text-ink/60">{body}</p><button type="button" className="mt-4 font-extrabold text-sky-dark">{action}</button></div></article>; }
function Section({ id, title, sub, children }: { id?: string; title: string; sub?: string; children: ReactNode }) { return <section id={id} className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="mb-9 max-w-2xl"><h2 className="text-4xl font-extrabold leading-tight sm:text-5xl">{title}</h2>{sub && <p className="mt-3 leading-7 text-ink/60">{sub}</p>}</div>{children}</section>; }
