import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BookOpen, Download, ExternalLink, Pencil, Plus, Trash2, Upload, X } from "lucide-react";
import toast from "react-hot-toast";
import { adminService } from "../../services/adminService";
import { gradesService } from "../../services/gradesService";
import { useLanguage } from "../../context/LanguageContext";
import type { TextBook } from "../../types";

type FormState = { gradeId: number; subjectId: number; title: string; description: string; orderNumber: number; isPublished: boolean; pdf?: File; thumbnail?: File };
const emptyForm: FormState = { gradeId: 0, subjectId: 0, title: "", description: "", orderNumber: 1, isPublished: true };
const messageFor = (error: unknown, fallback: string) => (error as { response?: { data?: { message?: string } } }).response?.data?.message || fallback;

export default function Textbooks() {
  const { t } = useLanguage(); const client = useQueryClient();
  const [form, setForm] = useState<FormState>(emptyForm); const [editing, setEditing] = useState<TextBook | null>(null); const [gradeFilter, setGradeFilter] = useState(0); const [subjectFilter, setSubjectFilter] = useState(0);
  const { data: grades = [], isLoading: loadingGrades } = useQuery({ queryKey: ["grades", "active"], queryFn: gradesService.getGrades, select: (items) => items.filter((grade) => grade.isActive) });
  const gradeForSubjects = form.gradeId || gradeFilter;
  const { data: availableSubjects = [], isLoading: loadingSubjects } = useQuery({ queryKey: ["grade-subjects", gradeForSubjects], queryFn: () => gradesService.getSubjectsForGrade(gradeForSubjects), enabled: Boolean(gradeForSubjects) });
  const { data: books = [], isLoading: loadingBooks, isError, refetch } = useQuery({ queryKey: ["admin-textbooks", gradeFilter, subjectFilter], queryFn: () => adminService.getTextbooks(gradeFilter || undefined, subjectFilter || undefined) });
  const invalidate = () => client.invalidateQueries({ queryKey: ["admin-textbooks"] });
  const save = useMutation({ mutationFn: (data: FormData) => editing ? adminService.updateTextbook(editing.id, data) : adminService.createTextbook(data), onSuccess: () => { invalidate(); setEditing(null); setForm(emptyForm); toast.success(t.admin.textbookUploaded); }, onError: (error) => toast.error(messageFor(error, t.common.error)) });
  const remove = useMutation({ mutationFn: adminService.deleteTextbook, onSuccess: invalidate, onError: () => toast.error(t.common.error) });
  const selectedSubjectName = useMemo(() => availableSubjects.find((subject) => subject.id === form.subjectId)?.name, [availableSubjects, form.subjectId]);
  const buildData = () => { const data = new FormData(); data.append("gradeId", String(form.gradeId)); data.append("subjectId", String(form.subjectId)); data.append("title", form.title.trim()); data.append("description", form.description); data.append("orderNumber", String(form.orderNumber)); data.append("isPublished", String(form.isPublished)); if (form.pdf) data.append("pdfFile", form.pdf); if (form.thumbnail) data.append("thumbnailFile", form.thumbnail); return data; };
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!form.gradeId || !form.subjectId) return toast.error(t.admin.selectGradeAndSubject); if (!editing && !form.pdf) return toast.error(t.admin.invalidPdf); if (form.pdf && form.pdf.type !== "application/pdf" && !form.pdf.name.toLowerCase().endsWith(".pdf")) return toast.error(t.admin.invalidPdf); save.mutate(buildData()); };
  const startEdit = (book: TextBook) => { setEditing(book); setForm({ gradeId: book.gradeId, subjectId: book.subjectId, title: book.title, description: book.description || "", orderNumber: book.orderNumber, isPublished: book.isPublished }); };
  const chooseGrade = (id: number) => { setForm((current) => ({ ...current, gradeId: id, subjectId: 0 })); };
  const chooseFilter = (id: number) => { setGradeFilter(id); setSubjectFilter(0); };
  return <div className="max-w-6xl mx-auto px-4 py-6 space-y-6"><div className="rounded-3xl bg-gradient-to-r from-indigo-950 to-purple-900 text-white p-7 shadow-xl"><div className="flex gap-3 items-center"><BookOpen /><div><h1 className="text-3xl font-black">{t.admin.textbooks}</h1><p className="text-sm text-white/70">{t.admin.textbooksSubtitle}</p></div></div></div>
    <form onSubmit={submit} className="bg-white rounded-3xl p-5 border border-ink/10 shadow-sm space-y-4"><div className="flex justify-between"><h2 className="font-black text-lg">{editing ? t.admin.editTextbook : t.admin.addTextbook}</h2>{editing && <button type="button" onClick={() => { setEditing(null); setForm(emptyForm); }}><X /></button>}</div><div className="grid sm:grid-cols-2 gap-3"><select value={form.gradeId} onChange={(event) => chooseGrade(Number(event.target.value))} required className="rounded-xl border-2 border-ink/10 p-3 text-sm"><option value={0}>{t.admin.selectGrade}</option>{grades.map((grade) => <option key={grade.id} value={grade.id}>{grade.displayName || grade.name}</option>)}</select><select value={form.subjectId} onChange={(event) => setForm({ ...form, subjectId: Number(event.target.value) })} required disabled={!form.gradeId || loadingSubjects} className="rounded-xl border-2 border-ink/10 p-3 text-sm"><option value={0}>{t.admin.selectSubject}</option>{availableSubjects.map((subject) => <option key={subject.id} value={subject.id}>{subject.name}</option>)}</select></div><div className="grid sm:grid-cols-2 gap-3"><input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder={t.admin.textbookTitle} className="rounded-xl border-2 border-ink/10 p-3 text-sm" /><input type="number" min="1" value={form.orderNumber} onChange={(event) => setForm({ ...form, orderNumber: Number(event.target.value) })} className="rounded-xl border-2 border-ink/10 p-3 text-sm" /></div><textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder={t.admin.description} className="w-full rounded-xl border-2 border-ink/10 p-3 text-sm" /><label className="block rounded-2xl border-2 border-dashed border-sky/30 bg-sky/5 p-4 cursor-pointer"><span className="font-bold text-sm flex gap-2 items-center"><Upload size={16} /> {t.admin.uploadPdf}</span><input type="file" accept="application/pdf,.pdf" className="sr-only" onChange={(event) => setForm({ ...form, pdf: event.target.files?.[0] })} />{form.pdf && <span className="block text-xs mt-2 text-emerald-700">{form.pdf.name} ({Math.ceil(form.pdf.size / 1024)} KB)</span>}</label><label className="flex gap-2 text-sm font-bold"><input type="checkbox" checked={form.isPublished} onChange={(event) => setForm({ ...form, isPublished: event.target.checked })} /> {t.admin.published}</label><button disabled={save.isPending || loadingGrades} className="rounded-xl bg-sky px-5 py-3 text-white font-black text-sm disabled:opacity-50">{save.isPending ? t.common.loading : <><Plus size={16} className="inline" /> {editing ? t.admin.save : t.admin.addTextbook}</>}</button>{selectedSubjectName && <span className="ml-3 text-xs text-ink/50">{selectedSubjectName}</span>}</form>
    <div className="bg-white rounded-3xl p-5 border border-ink/10 shadow-sm space-y-4"><div className="grid sm:grid-cols-2 gap-3"><select value={gradeFilter} onChange={(event) => chooseFilter(Number(event.target.value))} className="rounded-xl border-2 border-ink/10 p-3 text-sm"><option value={0}>{t.admin.selectGrade}</option>{grades.map((grade) => <option key={grade.id} value={grade.id}>{grade.displayName || grade.name}</option>)}</select><select value={subjectFilter} onChange={(event) => setSubjectFilter(Number(event.target.value))} disabled={!gradeFilter} className="rounded-xl border-2 border-ink/10 p-3 text-sm"><option value={0}>{t.admin.selectSubject}</option>{availableSubjects.map((subject) => <option key={subject.id} value={subject.id}>{subject.name}</option>)}</select></div>{loadingBooks ? <p>{t.common.loading}</p> : isError ? <button onClick={() => refetch()} className="text-coral font-bold">{t.common.retry}</button> : <div className="space-y-2">{books.map((book) => <div key={book.id} className="rounded-2xl border border-ink/10 p-4 flex justify-between gap-3"><div><h3 className="font-black">{book.title}</h3><p className="text-sm text-ink/60">{book.gradeName || book.gradeId} · {book.subjectName || book.subjectId} · #{book.orderNumber}</p><span className="text-xs font-bold text-emerald-700">{book.isPublished ? t.admin.published : t.admin.unpublished}</span></div><div className="flex h-fit"><a href={book.pdfUrl} target="_blank" rel="noopener noreferrer" className="p-2 text-sky"><ExternalLink size={17} /></a><a href={book.pdfUrl} download className="p-2 text-sky"><Download size={17} /></a><button onClick={() => startEdit(book)} className="p-2 text-sky"><Pencil size={17} /></button><button onClick={() => remove.mutate(book.id)} className="p-2 text-coral"><Trash2 size={17} /></button></div></div>)}{!books.length && <p className="text-ink/50 text-sm">{t.admin.noTextbooks}</p>}</div>}</div></div>;
}
